# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!
import sys
from SnifferBase import SnifferBase

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog, QTextEdit

class Ui_MainWindow(QtWidgets.QMainWindow,SnifferBase):


    # ====================================================================================================
    # Class Constructor
    # ====================================================================================================
	def __init__(self,parent = None):
		super(Ui_MainWindow, self).__init__()
		self.setupUi(self)
		self

    # ====================================================================================================
    # Function Button Select Log File
    # ==================================================================================================
	def onSelectLogFileBtnClick(self):
		try:
			logFile = QFileDialog.getOpenFileName()#("Output log file", "*.log"), ("all files", "*.*")
			SnifferBase.logFile = logFile
			if(None != SnifferBase.logFile and '' != SnifferBase.logFile):
				self.printActivity('> Output log: ' + str(logFile))
				self.textEdit_activityLog.moveCursor(QtGui.QTextCursor.End)
				self.textEdit_activityLog.insertPlainText('\n\n> Output log: ' + ''.join(logFile))
				QApplication.processEvents()
			else:
				self.printActivity('Output log file: Not specified!')
		except BaseException as e:
			self.printActivity('Ui_MainWindow:onSelectLogFileBtnClick() - No file selected' + str(e))

    # ====================================================================================================
    # Function Button Select Tod File
    # ====================================================================================================
	def onSelectTodFileBtnClick(self):
		try:
			todXmlFile = QFileDialog.getOpenFileName() #("ToD xml files", "*.xml"), ("all files", "*.*")))
			if(None != todXmlFile and '' != todXmlFile):
				self.printActivity('> ToD xml: ' + str(todXmlFile))
				self.textEdit_activityLog.moveCursor(QtGui.QTextCursor.End)
				self.textEdit_activityLog.insertPlainText('\n\n> ToD xml: ' + ''.join(todXmlFile))
				QApplication.processEvents()
			else:
				self.printActivity('ToD xml: Not specified!')
		except BaseException as e:
			self.printActivity('Ui_MainWindow:activityLogOuput() - ' + str(e))
    # ====================================================================================================
    # Function Configure UI
    # ====================================================================================================
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1572, 872)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.groupBox.setFont(font)
		self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.groupBox.setObjectName("groupBox")
		self.groupBox_portConfiguration = QtWidgets.QGroupBox(self.groupBox)
		self.groupBox_portConfiguration.setGeometry(QtCore.QRect(20, 20, 311, 131))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.groupBox_portConfiguration.setFont(font)
		self.groupBox_portConfiguration.setAlignment(QtCore.Qt.AlignCenter)
		self.groupBox_portConfiguration.setObjectName("groupBox_portConfiguration")
		self.label_comPort = QtWidgets.QLabel(self.groupBox_portConfiguration)
		self.label_comPort.setGeometry(QtCore.QRect(9, 30, 111, 21))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		font.setBold(False)
		font.setWeight(50)
		self.label_comPort.setFont(font)
		self.label_comPort.setObjectName("label_comPort")
		self.label_portRate = QtWidgets.QLabel(self.groupBox_portConfiguration)
		self.label_portRate.setGeometry(QtCore.QRect(10, 60, 111, 21))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.label_portRate.setFont(font)
		self.label_portRate.setObjectName("label_portRate")
		self.comBox_com1 = QtWidgets.QComboBox(self.groupBox_portConfiguration)
		self.comBox_com1.setGeometry(QtCore.QRect(150, 30, 121, 22))
		self.comBox_com1.setObjectName("comBox_com1")
		self.comBox_com1.addItem("")
		self.comBox_com1.addItem("")
		self.comBox_com1.addItem("")
		self.comBox_com1.addItem("")
		self.comBox_com1.addItem("")
		self.comBox_com1.addItem("")
		self.comBox_com1.addItem("")
		self.comBox_portRate = QtWidgets.QComboBox(self.groupBox_portConfiguration)
		self.comBox_portRate.setGeometry(QtCore.QRect(150, 60, 121, 22))
		self.comBox_portRate.setObjectName("comBox_portRate")
		self.comBox_portRate.addItem("")
		self.comBox_portRate.addItem("")
		self.comBox_portRate.addItem("")
		self.comBox_portRate.addItem("")
		self.comBox_portRate.addItem("")
		self.comBox_rspTime = QtWidgets.QComboBox(self.groupBox_portConfiguration)
		self.comBox_rspTime.setGeometry(QtCore.QRect(150, 90, 121, 22))
		self.comBox_rspTime.setObjectName("comBox_rspTime")
		self.comBox_rspTime.addItem("")
		self.comBox_rspTime.addItem("")
		self.comBox_rspTime.addItem("")
		self.comBox_rspTime.addItem("")
		self.comBox_rspTime.addItem("")
		self.comBox_rspTime.addItem("")
		self.comBox_rspTime.addItem("")
		self.comBox_rspTime.addItem("")
		self.comBox_rspTime.addItem("")
		self.comBox_rspTime.addItem("")
		self.label_rspTimeouts = QtWidgets.QLabel(self.groupBox_portConfiguration)
		self.label_rspTimeouts.setGeometry(QtCore.QRect(10, 90, 121, 20))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.label_rspTimeouts.setFont(font)
		self.label_rspTimeouts.setObjectName("label_rspTimeouts")
		self.groupBox_controlButtons = QtWidgets.QGroupBox(self.groupBox)
		self.groupBox_controlButtons.setGeometry(QtCore.QRect(350, 20, 511, 131))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.groupBox_controlButtons.setFont(font)
		self.groupBox_controlButtons.setAlignment(QtCore.Qt.AlignCenter)
		self.groupBox_controlButtons.setObjectName("groupBox_controlButtons")
		self.pushBtn_selectLogFile = QtWidgets.QPushButton(self.groupBox_controlButtons)
		self.pushBtn_selectLogFile.setGeometry(QtCore.QRect(10, 20, 121, 30))
		self.pushBtn_selectLogFile.clicked.connect(self.onSelectLogFileBtnClick)
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.pushBtn_selectLogFile.setFont(font)
		self.pushBtn_selectLogFile.setObjectName("pushBtn_selectLogFile")
		self.pushBtn_selectTodFile = QtWidgets.QPushButton(self.groupBox_controlButtons)
		self.pushBtn_selectTodFile.setGeometry(QtCore.QRect(10, 50, 121, 30))
		self.pushBtn_selectTodFile.clicked.connect(self.onSelectTodFileBtnClick)
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.pushBtn_selectTodFile.setFont(font)
		self.pushBtn_selectTodFile.setObjectName("pushBtn_selectTodFile")
		self.pushBtn_openLogFile = QtWidgets.QPushButton(self.groupBox_controlButtons)
		self.pushBtn_openLogFile.setGeometry(QtCore.QRect(10, 80, 121, 30))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.pushBtn_openLogFile.setFont(font)
		self.pushBtn_openLogFile.setObjectName("pushBtn_openLogFile")
		self.pushBtn_startSnif = QtWidgets.QPushButton(self.groupBox_controlButtons)
		self.pushBtn_startSnif.setGeometry(QtCore.QRect(130, 20, 111, 31))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.pushBtn_startSnif.setFont(font)
		self.pushBtn_startSnif.setObjectName("pushBtn_startSnif")
		self.pushBtn_changeBuff = QtWidgets.QPushButton(self.groupBox_controlButtons)
		self.pushBtn_changeBuff.setGeometry(QtCore.QRect(130, 50, 111, 31))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.pushBtn_changeBuff.setFont(font)
		self.pushBtn_changeBuff.setObjectName("pushBtn_changeBuff")
		self.pushBtn_changeMode = QtWidgets.QPushButton(self.groupBox_controlButtons)
		self.pushBtn_changeMode.setGeometry(QtCore.QRect(130, 80, 111, 31))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.pushBtn_changeMode.setFont(font)
		self.pushBtn_changeMode.setObjectName("pushBtn_changeMode")
		self.pushBtn_clrScrn = QtWidgets.QPushButton(self.groupBox_controlButtons)
		self.pushBtn_clrScrn.setGeometry(QtCore.QRect(240, 20, 111, 31))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.pushBtn_clrScrn.setFont(font)
		self.pushBtn_clrScrn.setObjectName("pushBtn_clrScrn")
		self.pushBtn_clrLogFile = QtWidgets.QPushButton(self.groupBox_controlButtons)
		self.pushBtn_clrLogFile.setGeometry(QtCore.QRect(240, 50, 111, 31))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.pushBtn_clrLogFile.setFont(font)
		self.pushBtn_clrLogFile.setObjectName("pushBtn_clrLogFile")
		self.pushBtn_clrCounters = QtWidgets.QPushButton(self.groupBox_controlButtons)
		self.pushBtn_clrCounters.setGeometry(QtCore.QRect(240, 80, 111, 31))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.pushBtn_clrCounters.setFont(font)
		self.pushBtn_clrCounters.setObjectName("pushBtn_clrCounters")
		self.pushBtn_analizeBusTraffic = QtWidgets.QPushButton(self.groupBox_controlButtons)
		self.pushBtn_analizeBusTraffic.setGeometry(QtCore.QRect(350, 20, 151, 31))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.pushBtn_analizeBusTraffic.setFont(font)
		self.pushBtn_analizeBusTraffic.setObjectName("pushBtn_analizeBusTraffic")
		self.pushBtn_drawGraph = QtWidgets.QPushButton(self.groupBox_controlButtons)
		self.pushBtn_drawGraph.setGeometry(QtCore.QRect(350, 50, 151, 31))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.pushBtn_drawGraph.setFont(font)
		self.pushBtn_drawGraph.setObjectName("pushBtn_drawGraph")
		self.pushBtn_traceOn = QtWidgets.QPushButton(self.groupBox_controlButtons)
		self.pushBtn_traceOn.setGeometry(QtCore.QRect(350, 80, 151, 31))
		font = QtGui.QFont()
		font.setFamily("Verdana")
		self.pushBtn_traceOn.setFont(font)
		self.pushBtn_traceOn.setAutoDefault(True)
		self.pushBtn_traceOn.setDefault(False)
		self.pushBtn_traceOn.setFlat(False)
		self.pushBtn_traceOn.setObjectName("pushBtn_traceOn")
		self.scrollArea_actvityLog = QtWidgets.QScrollArea(self.groupBox)
		self.scrollArea_actvityLog.setGeometry(QtCore.QRect(20, 180, 1231, 591))
		self.scrollArea_actvityLog.setWidgetResizable(True)
		self.scrollArea_actvityLog.setObjectName("scrollArea_actvityLog")
		self.scrollAreaWidgetContents = QtWidgets.QWidget()
		self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1229, 589))
		self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
		self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
		self.verticalScrollBar.setGeometry(QtCore.QRect(1205, 0, 21, 581))
		self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
		self.verticalScrollBar.setObjectName("verticalScrollBar")
		self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
		self.textEdit.setGeometry(QtCore.QRect(-7, -10, 1211, 591))
		self.textEdit.setObjectName("textEdit")
		self.scrollArea_actvityLog.setWidget(self.scrollAreaWidgetContents)
		self.groupBox_trafficStatistics = QtWidgets.QGroupBox(self.groupBox)
		self.groupBox_trafficStatistics.setGeometry(QtCore.QRect(1269, 20, 271, 761))
		self.groupBox_trafficStatistics.setObjectName("groupBox_trafficStatistics")
		self.groupBox_busActivity = QtWidgets.QGroupBox(self.groupBox_trafficStatistics)
		self.groupBox_busActivity.setGeometry(QtCore.QRect(10, 30, 251, 131))
		self.groupBox_busActivity.setAlignment(QtCore.Qt.AlignCenter)
		self.groupBox_busActivity.setFlat(False)
		self.groupBox_busActivity.setObjectName("groupBox_busActivity")
		self.label_busLoadPrcnt = QtWidgets.QLabel(self.groupBox_busActivity)
		self.label_busLoadPrcnt.setGeometry(QtCore.QRect(10, 40, 91, 16))
		self.label_busLoadPrcnt.setObjectName("label_busLoadPrcnt")
		self.label_detectedBytes = QtWidgets.QLabel(self.groupBox_busActivity)
		self.label_detectedBytes.setGeometry(QtCore.QRect(10, 60, 111, 16))
		self.label_detectedBytes.setObjectName("label_detectedBytes")
		self.label_decodedBytes = QtWidgets.QLabel(self.groupBox_busActivity)
		self.label_decodedBytes.setGeometry(QtCore.QRect(10, 80, 101, 16))
		self.label_decodedBytes.setObjectName("label_decodedBytes")
		self.label_droppedBytes = QtWidgets.QLabel(self.groupBox_busActivity)
		self.label_droppedBytes.setGeometry(QtCore.QRect(10, 100, 101, 16))
		self.label_droppedBytes.setObjectName("label_droppedBytes")
		self.label_valueBusLoad = QtWidgets.QLabel(self.groupBox_busActivity)
		self.label_valueBusLoad.setGeometry(QtCore.QRect(134, 40, 21, 20))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_valueBusLoad.setPalette(palette)
		self.label_valueBusLoad.setScaledContents(False)
		self.label_valueBusLoad.setWordWrap(False)
		self.label_valueBusLoad.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
		self.label_valueBusLoad.setObjectName("label_valueBusLoad")
		self.label_valueDtctdBytes = QtWidgets.QLabel(self.groupBox_busActivity)
		self.label_valueDtctdBytes.setGeometry(QtCore.QRect(134, 60, 51, 16))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_valueDtctdBytes.setPalette(palette)
		self.label_valueDtctdBytes.setObjectName("label_valueDtctdBytes")
		self.label_valueDcdBytes = QtWidgets.QLabel(self.groupBox_busActivity)
		self.label_valueDcdBytes.setGeometry(QtCore.QRect(134, 80, 41, 16))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_valueDcdBytes.setPalette(palette)
		self.label_valueDcdBytes.setObjectName("label_valueDcdBytes")
		self.label_valueDrpdBytes = QtWidgets.QLabel(self.groupBox_busActivity)
		self.label_valueDrpdBytes.setGeometry(QtCore.QRect(134, 100, 41, 16))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_valueDrpdBytes.setPalette(palette)
		self.label_valueDrpdBytes.setObjectName("label_valueDrpdBytes")
		self.groupBox_detectedFrames = QtWidgets.QGroupBox(self.groupBox_trafficStatistics)
		self.groupBox_detectedFrames.setGeometry(QtCore.QRect(10, 170, 251, 111))
		self.groupBox_detectedFrames.setAlignment(QtCore.Qt.AlignCenter)
		self.groupBox_detectedFrames.setFlat(False)
		self.groupBox_detectedFrames.setObjectName("groupBox_detectedFrames")
		self.label_intrFrames = QtWidgets.QLabel(self.groupBox_detectedFrames)
		self.label_intrFrames.setGeometry(QtCore.QRect(10, 40, 131, 16))
		self.label_intrFrames.setObjectName("label_intrFrames")
		self.label_notIntrFrames = QtWidgets.QLabel(self.groupBox_detectedFrames)
		self.label_notIntrFrames.setGeometry(QtCore.QRect(10, 60, 161, 16))
		self.label_notIntrFrames.setObjectName("label_notIntrFrames")
		self.label_unkwnParam = QtWidgets.QLabel(self.groupBox_detectedFrames)
		self.label_unkwnParam.setGeometry(QtCore.QRect(10, 80, 151, 16))
		self.label_unkwnParam.setObjectName("label_unkwnParam")
		self.label_valueintrFrames = QtWidgets.QLabel(self.groupBox_detectedFrames)
		self.label_valueintrFrames.setGeometry(QtCore.QRect(184, 40, 31, 16))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 106, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 56, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 106, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 56, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 127, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 106, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 56, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 42, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
		self.label_valueintrFrames.setPalette(palette)
		self.label_valueintrFrames.setObjectName("label_valueintrFrames")
		self.label_valueNotIntrFrames = QtWidgets.QLabel(self.groupBox_detectedFrames)
		self.label_valueNotIntrFrames.setGeometry(QtCore.QRect(184, 60, 31, 16))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_valueNotIntrFrames.setPalette(palette)
		self.label_valueNotIntrFrames.setObjectName("label_valueNotIntrFrames")
		self.label_valueUnkwnParam = QtWidgets.QLabel(self.groupBox_detectedFrames)
		self.label_valueUnkwnParam.setGeometry(QtCore.QRect(184, 80, 31, 16))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_valueUnkwnParam.setPalette(palette)
		self.label_valueUnkwnParam.setObjectName("label_valueUnkwnParam")
		self.groupBox_frameStatistics = QtWidgets.QGroupBox(self.groupBox_trafficStatistics)
		self.groupBox_frameStatistics.setGeometry(QtCore.QRect(10, 290, 251, 141))
		self.groupBox_frameStatistics.setAlignment(QtCore.Qt.AlignCenter)
		self.groupBox_frameStatistics.setFlat(False)
		self.groupBox_frameStatistics.setCheckable(False)
		self.groupBox_frameStatistics.setChecked(False)
		self.groupBox_frameStatistics.setObjectName("groupBox_frameStatistics")
		self.label_todReads = QtWidgets.QLabel(self.groupBox_frameStatistics)
		self.label_todReads.setGeometry(QtCore.QRect(10, 40, 81, 16))
		self.label_todReads.setObjectName("label_todReads")
		self.label_todWrites = QtWidgets.QLabel(self.groupBox_frameStatistics)
		self.label_todWrites.setGeometry(QtCore.QRect(10, 60, 81, 16))
		self.label_todWrites.setObjectName("label_todWrites")
		self.label_todNacks = QtWidgets.QLabel(self.groupBox_frameStatistics)
		self.label_todNacks.setGeometry(QtCore.QRect(10, 80, 55, 16))
		self.label_todNacks.setObjectName("label_todNacks")
		self.label_othersCmds = QtWidgets.QLabel(self.groupBox_frameStatistics)
		self.label_othersCmds.setGeometry(QtCore.QRect(10, 100, 91, 16))
		self.label_othersCmds.setObjectName("label_othersCmds")
		self.label_ReqResp = QtWidgets.QLabel(self.groupBox_frameStatistics)
		self.label_ReqResp.setGeometry(QtCore.QRect(100, 20, 71, 21))
		font = QtGui.QFont()
		font.setPointSize(7)
		self.label_ReqResp.setFont(font)
		self.label_ReqResp.setObjectName("label_ReqResp")
		self.label_todReadsReq = QtWidgets.QLabel(self.groupBox_frameStatistics)
		self.label_todReadsReq.setGeometry(QtCore.QRect(110, 40, 21, 21))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_todReadsReq.setPalette(palette)
		self.label_todReadsReq.setObjectName("label_todReadsReq")
		self.label_valueTodNacks = QtWidgets.QLabel(self.groupBox_frameStatistics)
		self.label_valueTodNacks.setGeometry(QtCore.QRect(110, 80, 16, 16))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_valueTodNacks.setPalette(palette)
		self.label_valueTodNacks.setObjectName("label_valueTodNacks")
		self.label_valueOthersCmds = QtWidgets.QLabel(self.groupBox_frameStatistics)
		self.label_valueOthersCmds.setGeometry(QtCore.QRect(110, 100, 16, 16))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_valueOthersCmds.setPalette(palette)
		self.label_valueOthersCmds.setObjectName("label_valueOthersCmds")
		self.label_todWritesReq = QtWidgets.QLabel(self.groupBox_frameStatistics)
		self.label_todWritesReq.setGeometry(QtCore.QRect(110, 60, 20, 20))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_todWritesReq.setPalette(palette)
		self.label_todWritesReq.setObjectName("label_todWritesReq")
		self.label__todReadsResp = QtWidgets.QLabel(self.groupBox_frameStatistics)
		self.label__todReadsResp.setGeometry(QtCore.QRect(140, 40, 21, 21))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label__todReadsResp.setPalette(palette)
		self.label__todReadsResp.setObjectName("label__todReadsResp")
		self.label_todWritesResp = QtWidgets.QLabel(self.groupBox_frameStatistics)
		self.label_todWritesResp.setGeometry(QtCore.QRect(140, 60, 20, 20))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_todWritesResp.setPalette(palette)
		self.label_todWritesResp.setObjectName("label_todWritesResp")
		self.groupBox_sniffConfig = QtWidgets.QGroupBox(self.groupBox_trafficStatistics)
		self.groupBox_sniffConfig.setGeometry(QtCore.QRect(10, 440, 251, 91))
		self.groupBox_sniffConfig.setAlignment(QtCore.Qt.AlignCenter)
		self.groupBox_sniffConfig.setFlat(False)
		self.groupBox_sniffConfig.setCheckable(False)
		self.groupBox_sniffConfig.setChecked(False)
		self.groupBox_sniffConfig.setObjectName("groupBox_sniffConfig")
		self.label_buffType = QtWidgets.QLabel(self.groupBox_sniffConfig)
		self.label_buffType.setGeometry(QtCore.QRect(10, 26, 91, 20))
		self.label_buffType.setObjectName("label_buffType")
		self.label_sniffMode = QtWidgets.QLabel(self.groupBox_sniffConfig)
		self.label_sniffMode.setGeometry(QtCore.QRect(10, 56, 91, 20))
		self.label_sniffMode.setObjectName("label_sniffMode")
		self.label_sniffModeOnTheFly = QtWidgets.QLabel(self.groupBox_sniffConfig)
		self.label_sniffModeOnTheFly.setGeometry(QtCore.QRect(110, 50, 71, 31))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_sniffModeOnTheFly.setPalette(palette)
		self.label_sniffModeOnTheFly.setObjectName("label_sniffModeOnTheFly")
		self.label_buffTypeRam = QtWidgets.QLabel(self.groupBox_sniffConfig)
		self.label_buffTypeRam.setGeometry(QtCore.QRect(110, 20, 51, 31))
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		self.label_buffTypeRam.setPalette(palette)
		self.label_buffTypeRam.setObjectName("label_buffTypeRam")
		self.groupBox_todFilters = QtWidgets.QGroupBox(self.groupBox)
		self.groupBox_todFilters.setGeometry(QtCore.QRect(880, 20, 371, 131))
		self.groupBox_todFilters.setAlignment(QtCore.Qt.AlignCenter)
		self.groupBox_todFilters.setObjectName("groupBox_todFilters")
		self.pushBtn_enableToDFilters = QtWidgets.QPushButton(self.groupBox_todFilters)
		self.pushBtn_enableToDFilters.setGeometry(QtCore.QRect(10, 20, 61, 31))
		self.pushBtn_enableToDFilters.setObjectName("pushBtn_enableToDFilters")
		self.pushBtn_addToDFilters = QtWidgets.QPushButton(self.groupBox_todFilters)
		self.pushBtn_addToDFilters.setGeometry(QtCore.QRect(80, 20, 71, 31))
		self.pushBtn_addToDFilters.setObjectName("pushBtn_addToDFilters")
		self.pushBtn_clrToDFilters = QtWidgets.QPushButton(self.groupBox_todFilters)
		self.pushBtn_clrToDFilters.setGeometry(QtCore.QRect(160, 20, 61, 31))
		self.pushBtn_clrToDFilters.setObjectName("pushBtn_clrToDFilters")
		self.label_activToDFilters = QtWidgets.QLabel(self.groupBox_todFilters)
		self.label_activToDFilters.setGeometry(QtCore.QRect(250, 20, 111, 31))
		self.label_activToDFilters.setObjectName("label_activToDFilters")
		self.label_fctUnitToDFilters = QtWidgets.QLabel(self.groupBox_todFilters)
		self.label_fctUnitToDFilters.setGeometry(QtCore.QRect(10, 60, 71, 21))
		self.label_fctUnitToDFilters.setObjectName("label_fctUnitToDFilters")
		self.label_zoneToDFilters = QtWidgets.QLabel(self.groupBox_todFilters)
		self.label_zoneToDFilters.setGeometry(QtCore.QRect(80, 60, 71, 21))
		self.label_zoneToDFilters.setObjectName("label_zoneToDFilters")
		self.label_objToDFilters = QtWidgets.QLabel(self.groupBox_todFilters)
		self.label_objToDFilters.setGeometry(QtCore.QRect(160, 60, 51, 21))
		self.label_objToDFilters.setObjectName("label_objToDFilters")
		self.label_paramToDFilters = QtWidgets.QLabel(self.groupBox_todFilters)
		self.label_paramToDFilters.setGeometry(QtCore.QRect(250, 60, 71, 21))
		self.label_paramToDFilters.setObjectName("label_paramToDFilters")
		self.combBox_obj = QtWidgets.QComboBox(self.groupBox_todFilters)
		self.combBox_obj.setGeometry(QtCore.QRect(160, 90, 61, 22))
		self.combBox_obj.setObjectName("combBox_obj")
		self.combBox_obj.addItem("")
		self.combBox_fctUnit = QtWidgets.QComboBox(self.groupBox_todFilters)
		self.combBox_fctUnit.setGeometry(QtCore.QRect(10, 90, 61, 22))
		self.combBox_fctUnit.setObjectName("combBox_fctUnit")
		self.combBox_fctUnit.addItem("")
		self.combBox_zone = QtWidgets.QComboBox(self.groupBox_todFilters)
		self.combBox_zone.setGeometry(QtCore.QRect(80, 90, 71, 22))
		self.combBox_zone.setObjectName("combBox_zone")
		self.combBox_zone.addItem("")
		self.lineEdit_paramToDFilters = QtWidgets.QLineEdit(self.groupBox_todFilters)
		self.lineEdit_paramToDFilters.setGeometry(QtCore.QRect(250, 90, 113, 22))
		self.lineEdit_paramToDFilters.setText("")
		self.lineEdit_paramToDFilters.setObjectName("lineEdit_paramToDFilters")
		self.groupBox_activityLog = QtWidgets.QGroupBox(self.groupBox)
		self.groupBox_activityLog.setGeometry(QtCore.QRect(9, 160, 1251, 621))
		self.groupBox_activityLog.setAlignment(QtCore.Qt.AlignCenter)
		self.groupBox_activityLog.setObjectName("groupBox_activityLog")
		self.textEdit_activityLog = QtWidgets.QTextEdit(self.groupBox_activityLog)
		self.textEdit_activityLog.setGeometry(QtCore.QRect(12, 30, 1203, 580))
		self.textEdit_activityLog.setObjectName("textEdit_activityLog")
		self.horizontalLayout.addWidget(self.groupBox)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1572, 26))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		
		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "ASP BUS SNIFFER TOOL QT v0.1"))
		self.groupBox.setTitle(_translate("MainWindow", "ASP BUS SNIFFER"))
		self.groupBox_portConfiguration.setTitle(_translate("MainWindow", "Port Configuration"))
		self.label_comPort.setText(_translate("MainWindow", "Com Port [N#]"))
		self.label_portRate.setText(_translate("MainWindow", "Port Rate [kb/s]"))
		self.comBox_com1.setCurrentText(_translate("MainWindow", "COM1"))
		self.comBox_com1.setItemText(0, _translate("MainWindow", "COM1"))
		self.comBox_com1.setItemText(1, _translate("MainWindow", "COM2"))
		self.comBox_com1.setItemText(2, _translate("MainWindow", "COM3"))
		self.comBox_com1.setItemText(3, _translate("MainWindow", "COM4"))
		self.comBox_com1.setItemText(4, _translate("MainWindow", "COM5"))
		self.comBox_com1.setItemText(5, _translate("MainWindow", "COM6"))
		self.comBox_com1.setItemText(6, _translate("MainWindow", "COM7"))
		self.comBox_portRate.setItemText(0, _translate("MainWindow", "9600"))
		self.comBox_portRate.setItemText(1, _translate("MainWindow", "19200"))
		self.comBox_portRate.setItemText(2, _translate("MainWindow", "38400"))
		self.comBox_portRate.setItemText(3, _translate("MainWindow", "57600"))
		self.comBox_portRate.setItemText(4, _translate("MainWindow", "115200"))
		self.comBox_rspTime.setItemText(0, _translate("MainWindow", "100"))
		self.comBox_rspTime.setItemText(1, _translate("MainWindow", "200"))
		self.comBox_rspTime.setItemText(2, _translate("MainWindow", "300"))
		self.comBox_rspTime.setItemText(3, _translate("MainWindow", "400"))
		self.comBox_rspTime.setItemText(4, _translate("MainWindow", "500"))
		self.comBox_rspTime.setItemText(5, _translate("MainWindow", "600"))
		self.comBox_rspTime.setItemText(6, _translate("MainWindow", "700"))
		self.comBox_rspTime.setItemText(7, _translate("MainWindow", "800"))
		self.comBox_rspTime.setItemText(8, _translate("MainWindow", "900"))
		self.comBox_rspTime.setItemText(9, _translate("MainWindow", "1000"))
		self.label_rspTimeouts.setText(_translate("MainWindow", "Rsp Timeout [ms]"))
		self.groupBox_controlButtons.setTitle(_translate("MainWindow", "Control Buttons"))
		self.pushBtn_selectLogFile.setText(_translate("MainWindow", "Select Log File"))
		self.pushBtn_selectTodFile.setText(_translate("MainWindow", "Select ToD File"))
		self.pushBtn_openLogFile.setText(_translate("MainWindow", "Open Log File"))
		self.pushBtn_startSnif.setText(_translate("MainWindow", "Start"))
		self.pushBtn_changeBuff.setText(_translate("MainWindow", "Change Buffer"))
		self.pushBtn_changeMode.setText(_translate("MainWindow", "Change Mode"))
		self.pushBtn_clrScrn.setText(_translate("MainWindow", "Clear Screen"))
		self.pushBtn_clrLogFile.setText(_translate("MainWindow", "Clear Log File"))
		self.pushBtn_clrCounters.setText(_translate("MainWindow", "Clear Counters"))
		self.pushBtn_analizeBusTraffic.setText(_translate("MainWindow", "Analize BusTraffic"))
		self.pushBtn_drawGraph.setText(_translate("MainWindow", "Draw Graphics"))
		self.pushBtn_traceOn.setText(_translate("MainWindow", "Trace On"))
		self.groupBox_trafficStatistics.setTitle(_translate("MainWindow", "Traffic Statistics"))
		self.groupBox_busActivity.setTitle(_translate("MainWindow", "Bus Activity"))
		self.label_busLoadPrcnt.setText(_translate("MainWindow", "Bus Load %:"))
		self.label_detectedBytes.setText(_translate("MainWindow", "Detected Bytes:"))
		self.label_decodedBytes.setText(_translate("MainWindow", "Decoded Bytes:"))
		self.label_droppedBytes.setText(_translate("MainWindow", "Dropped Bytes:"))
		self.label_valueBusLoad.setText(_translate("MainWindow", "0"))
		self.label_valueDtctdBytes.setText(_translate("MainWindow", "0"))
		self.label_valueDcdBytes.setText(_translate("MainWindow", "0"))
		self.label_valueDrpdBytes.setText(_translate("MainWindow", "0.00"))
		self.groupBox_detectedFrames.setTitle(_translate("MainWindow", "Detected Frames"))
		self.label_intrFrames.setText(_translate("MainWindow", "Interpreted Frames:"))
		self.label_notIntrFrames.setText(_translate("MainWindow", "Not Interpreted Frames: "))
		self.label_unkwnParam.setText(_translate("MainWindow", "Unknown Parameters:"))
		self.label_valueintrFrames.setText(_translate("MainWindow", "0"))
		self.label_valueNotIntrFrames.setText(_translate("MainWindow", "0"))
		self.label_valueUnkwnParam.setText(_translate("MainWindow", "0"))
		self.groupBox_frameStatistics.setTitle(_translate("MainWindow", "Frame Statistics"))
		self.label_todReads.setText(_translate("MainWindow", "ToD Reads:"))
		self.label_todWrites.setText(_translate("MainWindow", "ToD Writes:"))
		self.label_todNacks.setText(_translate("MainWindow", "Nacks:"))
		self.label_othersCmds.setText(_translate("MainWindow", "Others Cmds:"))
		self.label_ReqResp.setText(_translate("MainWindow", "  Req  Res"))
		self.label_todReadsReq.setText(_translate("MainWindow", "0"))
		self.label_valueTodNacks.setText(_translate("MainWindow", "0"))
		self.label_valueOthersCmds.setText(_translate("MainWindow", "0"))
		self.label_todWritesReq.setText(_translate("MainWindow", "0"))
		self.label__todReadsResp.setText(_translate("MainWindow", "0"))
		self.label_todWritesResp.setText(_translate("MainWindow", "0"))
		self.groupBox_sniffConfig.setTitle(_translate("MainWindow", "Sniffer Configuration"))
		self.label_buffType.setText(_translate("MainWindow", "Buffer Type:"))
		self.label_sniffMode.setText(_translate("MainWindow", "Sniffer Mode: "))
		self.label_sniffModeOnTheFly.setText(_translate("MainWindow", "OnTheFly"))
		self.label_buffTypeRam.setText(_translate("MainWindow", "RAM"))
		self.groupBox_todFilters.setTitle(_translate("MainWindow", "ToD Filters"))
		self.pushBtn_enableToDFilters.setText(_translate("MainWindow", "Enable"))
		self.pushBtn_addToDFilters.setText(_translate("MainWindow", "Add"))
		self.pushBtn_clrToDFilters.setText(_translate("MainWindow", "Clear"))
		self.label_activToDFilters.setText(_translate("MainWindow", "ToD Filters: 1"))
		self.label_fctUnitToDFilters.setText(_translate("MainWindow", " Fct Unit"))
		self.label_zoneToDFilters.setText(_translate("MainWindow", " Zone"))
		self.label_objToDFilters.setText(_translate("MainWindow", " Object"))
		self.label_paramToDFilters.setText(_translate("MainWindow", "Parameter"))
		self.combBox_obj.setItemText(0, _translate("MainWindow", ".+"))
		self.combBox_fctUnit.setItemText(0, _translate("MainWindow", ".+"))
		self.combBox_zone.setItemText(0, _translate("MainWindow", ".+"))
		self.groupBox_activityLog.setTitle(_translate("MainWindow", "Activity Log"))
